id: AC2F293D5
title: 'Divine Blue Water: A Contamination Purifying Smoke Offering by the Great Master
  Padmasambhava'
type: translation
pechas:
- I84144C6F
- I4B4ACAE6
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:49:56.463531
  last_modified_at: 2023-01-04 11:49:56.463547
  collections:
  - Dudjom Rinpoche Series
  - Works of Tibetan Masters
alignment_to_base:
  I84144C6F/0DE9: '9143'
  I4B4ACAE6/1EE4: '9143'
